language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install: pip install -r devel-requirements.txt
install: pip install -r requirements.txt

script: pylint rmock

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
